namespace: app

api:
  image: ghcr.io/4b93f-organization/k8s-log-processor-api:latest
  replicas: 1
  resources:
    requests:
      cpu: "250m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  service:
    type: NodePort
    port: 8000
  env:
    AWS_ENDPOINT_URL: "http://host.minikube.internal:4566"
    AWS_REGION: "us-east-1"
    AWS_ACCESS_KEY_ID: "placeholder"
    AWS_SECRET_ACCESS_KEY: "placeholder"
    SQS_QUEUE_URL: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/log-processing"
    S3_BUCKET: "log-processing"

worker:
  image: ghcr.io/4b93f-organization/k8s-log-processor-worker:latest
  replicas: 2
  resources:
    requests:
      cpu: "250m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  metrics:
    enabled: true
    port: 8000
  env:
    SQS_QUEUE_URL: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/log-processing"
    AWS_ACCESS_KEY_ID: "placeholder"
    AWS_SECRET_ACCESS_KEY: "placeholder"
    AWS_ENDPOINT_URL: "http://host.minikube.internal:4566"
    AWS_REGION: "us-east-1"
