apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ghcr.io/4b93f-organization/k8s-prod-api:latest
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
        env:
        - name: AWS_ENDPOINT_URL
          value: "http://host.minikube.internal:4566"
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_ACCESS_KEY_ID
          value: "placeholder"
        - name: AWS_SECRET_ACCESS_KEY
          value: "placeholder"
        - name: SQS_QUEUE_URL
          value: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/sqs-queue"
        - name: S3_BUCKET
          value: "log-processing"