apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/4b93f-organization/k8s-prod-worker:latest
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: '1'
              memory: 512Mi
          env:
            - name: SQS_QUEUE_URL
              value: http://placeholder
            - name: AWS_ACCESS_KEY_ID
              value: placeholder
            - name: AWS_SECRET_ACCESS_KEY
              value: placeholder
            - name: AWS_ENDPOINT_URL
              value: http://host.minikube.internal:4566
            - name: AWS_REGION
              value: us-east-1